apiVersion: v1.0
kind: Service
metadata:
  name: authservice2
  namespace: chatgut
spec:
  ports:
   - port: 8004
     targetPort: 8004
     selector:
       app: authservice2
       clusterIP: None
---

apiVersion: apps/v1.0
kind: Deployment
metadata:
  name: authservice2
  labels:
    app: authservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice2
  template:
    metadata:
      name: authservice2
      labels:
        app: authservice2
    spec:
      containers:
        - name: authservice2
          image: urlshortenerservice-url
          imagePullPolicy: Never
          ports:
            - containerPort: 8004
              name: authservice2
      restartPolicy: Always
