version: "3.9"
services:
  url:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_URL: redis
    ports:
      - "8004:8080"
  redis:
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

